before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame

language: python

python:

  - "2.7"

script: 

  - python MapGen/MapGen.py
